name: service1-build-and-push

on: [ push, pull_request ]

env:
  SERVICE_NAME: "service1"

jobs:
  check-if-pr:
    runs-on: ubuntu-latest
    outputs:
      pr_number: "123"

    steps:
      - run: exit 1

  has-changed:
    runs-on: ubuntu-latest
    needs: check-if-pr
    outputs:
      image_tag: ${{ steps.set-image-tag.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - uses: actions/checkout@v2
        with:
          clean: false

      # TODO: prod as default "prod" tag?
      - id: set-image-tag
        # check if anything has changed, which is not already in main (git diff)
        # grep return == 0 => has changes (&& part),
        # grep return == 1 => no changes (|| part)
        run: |
          git diff --name-only `git rev-parse origin/main` HEAD | grep ^${{ env.SERVICE_NAME }}/ &&\
            HAS_CHANGES=1 || HAS_CHANGES=0
          [ $HAS_CHANGES -eq 1 ] && echo "::set-output name=image_tag::${{ github.sha }}" || echo "::set-output name=image_tag::prod"

  build-and-push:
    runs-on: ubuntu-latest
    needs: has-changed
    steps:
      - uses: actions/checkout@v2
      - name: Build and push on change
        if: needs.has-changed.outputs.image_tag != 'prod'
        run: |
          echo "build and push with new tag '${{ needs.has-changed.outputs.image_tag }}'."

  tag_for_pr:
    runs-on: ubuntu-latest
    needs: [ has-changed, build-and-push ]
    steps:
      - uses: actions/checkout@v2
      - name: Retag respective image
        run: echo "do some tagging - from '${{ needs.has-changed.outputs.image_tag }}' to 'pr-XY'."
