name: service1-build-and-push

on: [push, pull_request]

env:
  SERVICE_NAME: "service1"

jobs:
  has-changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - uses: actions/checkout@v2
      # check if anything has changed, which is not already in main
      - name: has-changed
        # grep return == 0 => gibt changes (steps.has_changed.outcome=success),
        # grep return == 1 => keine changes (steps.has_changed.outcome=failure)
        run: git diff --name-only `git rev-parse main` HEAD | grep ${{ env.SERVICE_NAME }}
        continue-on-error: true

      # TODO: prod as default "prod" tag?
      - run: echo "::set-output name=image_tag::prod"
        if: steps.has-changed.outcome == 'failure'

      - run: echo "::set-output name=image_tag::${{ github.sha }}"
        if: steps.has-changed.outcome == 'success'

  build-and-push:
    runs-on: ubuntu-latest
    needs: has-changed
    if: needs.has-changed.outputs.image_tag != 'prod'
    steps:
      - uses: actions/checkout@v2
      - name: Build and push on change
        run: |
          echo "build and push with new tag '${{ github.sha }}.'"

  tag_for_test:
    runs-on: ubuntu-latest
    needs: [has-changed, build-and-push]
    steps:
      - uses: actions/checkout@v2
      - name: Retag respective image
        run: echo "do some tagging - from ${{ needs.has-changed.outputs.image_tag }} to test."
